"""empty message

Revision ID: a46b50d540db
Revises: 
Create Date: 2018-08-27 09:40:11.019825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46b50d540db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Patidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estadio', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('gols_casa', sa.Integer(), nullable=True),
    sa.Column('gols_visitante', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeTime', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomeTime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Times')
    op.drop_table('Patidas')
    # ### end Alembic commands ###
