"""empty message

Revision ID: bd1ea5345823
Revises: a46b50d540db
Create Date: 2018-08-27 09:44:54.606141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ea5345823'
down_revision = 'a46b50d540db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patidas', sa.Column('id_casa', sa.Integer(), nullable=True))
    op.add_column('Patidas', sa.Column('id_visitante', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Patidas', 'Times', ['id_visitante'], ['id'])
    op.create_foreign_key(None, 'Patidas', 'Times', ['id_casa'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Patidas', type_='foreignkey')
    op.drop_constraint(None, 'Patidas', type_='foreignkey')
    op.drop_column('Patidas', 'id_visitante')
    op.drop_column('Patidas', 'id_casa')
    # ### end Alembic commands ###
